# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

workspace 'Talabaty'

def globalDependances
  pod 'NotificationBannerSwift'
  pod 'Kingfisher'
  pod 'NVActivityIndicatorView'
  pod 'MOLH'
end

def rxDependances
  pod 'RxSwift'
  pod 'RxCocoa'
end

target 'TalabatyCore' do
  project 'SubProjects/TalabatyCore/TalabatyCore.xcodeproj'
  
  # Pods for TalabatyCore
  globalDependances
  rxDependances
  
end

target 'TalabatyUI' do
  project 'SubProjects/TalabatyUI/TalabatyUI.xcodeproj'
  
  # Pods for TalabatyUI
  
end

target 'Talabaty' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Talabaty
  globalDependances
  rxDependances
  
  pod 'FLEX'
  
  post_install do |installer|
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
      end
    end
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
    
    xcode_base_version = `xcodebuild -version | grep 'Xcode' | awk '{print $2}' | cut -d . -f 1`
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.base_configuration_reference && Integer(xcode_base_version) >= 14
          xcconfig_path = config.base_configuration_reference.real_path
          xcconfig = File.read(xcconfig_path)
          xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
          File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
        end
      end
    end
  end
end

